# Generated by Django 5.2.8 on 2025-12-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(default='', help_text='Title of the problem', max_length=255),
        ),
    ]
