# Generated by Django 5.2.8 on 2025-12-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_codeblock_imports_codeblock_runner_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='display_testcase',
            field=models.BooleanField(default=False),
        ),
    ]
