# Generated by Django 5.2.8 on 2026-06-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0015_problem_custom_validator_problem_validator_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="generator_code",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Python test case generator script for programmatic generation",
            ),
        ),
    ]
