# Generated by Django 5.2.8 on 2026-08-22 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0017_clean_time_markers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="downvotes",
            field=models.ManyToManyField(
                blank=True,
                related_name="disliked_problems",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_problems", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="views",
            field=models.PositiveIntegerField(
                default=0, help_text="Total views for this problem"
            ),
        ),
    ]
