# Generated by Django 5.2.8 on 2026-08-22 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0018_problem_downvotes_problem_upvotes_problem_views"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_problems",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
