# Generated by Django 5.2.8 on 2026-08-22 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscussPost",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Discussion"),
                            ("INTERVIEW_EXPERIENCE", "Interview Experience"),
                            ("INTERVIEW_QUESTION", "Interview Question"),
                            ("CAREER", "Career & Growth"),
                            ("COMPENSATION", "Compensation"),
                            ("FEEDBACK", "Feedback & Suggestions"),
                        ],
                        db_index=True,
                        default="GENERAL",
                        max_length=30,
                    ),
                ),
                ("content", models.TextField(help_text="Post body in Markdown format")),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of string tags, e.g. ['Google', 'System Design']",
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discuss_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "downvotes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="downvoted_general_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "upvotes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="upvoted_general_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Discuss Post",
                "verbose_name_plural": "Discuss Posts",
                "db_table": "discuss_post",
                "ordering": ["-pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscussComment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discuss_post_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="discuss.discusscomment",
                    ),
                ),
                (
                    "upvotes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="upvoted_general_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="discuss.discusspost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discuss Comment",
                "verbose_name_plural": "Discuss Comments",
                "db_table": "discuss_comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="discusspost",
            index=models.Index(
                fields=["category", "-created_at"],
                name="discuss_pos_categor_504d60_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discusspost",
            index=models.Index(
                fields=["pinned", "-created_at"], name="discuss_pos_pinned_c8cb95_idx"
            ),
        ),
    ]
