# Generated by Django 5.2.8 on 2026-08-22 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discuss", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="discusscomment",
            name="downvotes",
            field=models.ManyToManyField(
                blank=True,
                related_name="downvoted_general_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
