# Generated by Django 5.2.8 on 2026-08-22 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("problem", "0017_clean_time_markers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Title of the contest. If left blank, auto-increments to 'Weekly run <number>'",
                        max_length=255,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "is_weekly",
                    models.BooleanField(
                        default=True,
                        help_text="True if this is an official Weekly Run contest",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Start date and time of the contest"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=90, help_text="Contest duration in minutes"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="End date and time (automatically computed from duration if blank)",
                        null=True,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contest",
                "verbose_name_plural": "Contests",
                "db_table": "contest",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ContestParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        default=0, help_text="Total contest points earned"
                    ),
                ),
                (
                    "penalty_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Penalty in seconds from wrong submissions"
                    ),
                ),
                (
                    "finish_time_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Seconds from contest start to last AC"
                    ),
                ),
                ("problems_solved", models.PositiveIntegerField(default=0)),
                ("problem_details", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="contest.contest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contest Participant Score",
                "verbose_name_plural": "Contest Participant Scores",
                "db_table": "contest_participant",
                "ordering": ["-score", "penalty_seconds", "finish_time_seconds"],
            },
        ),
        migrations.CreateModel(
            name="ContestProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, help_text="Order in contest (1=Q1, 2=Q2, etc.)"
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Score points awarded for solving this problem",
                    ),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_problems",
                        to="contest.contest",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_assignments",
                        to="problem.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contest Problem",
                "verbose_name_plural": "Contest Problems",
                "db_table": "contest_problem",
                "ordering": ["contest", "order"],
            },
        ),
        migrations.CreateModel(
            name="ContestRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="contest.contest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contest Registration",
                "verbose_name_plural": "Contest Registrations",
                "db_table": "contest_registration",
            },
        ),
        migrations.CreateModel(
            name="ContestSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUE", "In Queue"),
                            ("PROCESSING", "Processing"),
                            ("Accepted", "Accepted"),
                            ("Wrong Answer", "Wrong Answer"),
                            ("Time Limit Exceeded", "Time Limit Exceeded"),
                            ("Compilation Error", "Compilation Error"),
                            ("Runtime Error (SIGSEGV)", "Runtime Error (SIGSEGV)"),
                            ("Runtime Error (SIGXFSZ)", "Runtime Error (SIGXFSZ)"),
                            ("Runtime Error (SIGFPE)", "Runtime Error (SIGFPE)"),
                            ("Runtime Error (SIGABRT)", "Runtime Error (SIGABRT)"),
                            ("Runtime Error (NZEC)", "Runtime Error (NZEC)"),
                            ("Runtime Error (Other)", "Runtime Error (Other)"),
                            ("Internal Error", "Internal Error"),
                            ("Exec Format Error", "Exec Format Error"),
                            ("Invalid Testcase", "Invalid Testcase"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_accepted", models.BooleanField(default=False)),
                (
                    "time_taken_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Seconds from contest start"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_submissions",
                        to="contest.contest",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_submissions",
                        to="problem.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contest Submission",
                "verbose_name_plural": "Contest Submissions",
                "db_table": "contest_submission",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contest",
            index=models.Index(
                fields=["start_time", "end_time"], name="contest_start_t_625dfe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contest",
            index=models.Index(
                fields=["is_weekly", "is_published"], name="contest_is_week_3c8802_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contestparticipant",
            index=models.Index(
                fields=["contest", "-score", "penalty_seconds", "finish_time_seconds"],
                name="contest_par_contest_57917d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contestparticipant",
            unique_together={("contest", "user")},
        ),
        migrations.AddIndex(
            model_name="contestproblem",
            index=models.Index(
                fields=["contest", "order"], name="contest_pro_contest_b18eb0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contestproblem",
            unique_together={("contest", "order"), ("contest", "problem")},
        ),
        migrations.AddIndex(
            model_name="contestregistration",
            index=models.Index(
                fields=["contest", "user"], name="contest_reg_contest_878f4a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contestregistration",
            unique_together={("contest", "user")},
        ),
        migrations.AddIndex(
            model_name="contestsubmission",
            index=models.Index(
                fields=["contest", "problem"], name="contest_sub_contest_8d5e5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contestsubmission",
            index=models.Index(
                fields=["contest", "user"], name="contest_sub_contest_a2519f_idx"
            ),
        ),
    ]
